name = "cepheus-onl"
main = ".open-next/worker.js"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[vars]
DB_BINDING = "DB"

[[d1_databases]]
binding = "DB"
database_name = "cepheus-onl-db"
database_id = "18e5b778-b1cb-4c67-9ec5-4f07e21715a1"
preview_database_id = "cepheus-onl-db-preview"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cepheus-onl-cache"

[site]
bucket = ".open-next/assets"
