export const archetypes = [
  'A grizzled veteran of a long-forgotten war.',
  'A naive farmhand from a backwater planet on their first trip off-world.',
  'A slick corporate agent with a hidden agenda.',
  "A disgraced noble looking to reclaim their family's honor.",
  'An inquisitive scientist obsessed with a strange cosmic anomaly.',
  'A hard-bitten mercenary who only cares about the next paycheck.',
  'A devout cleric of a strange space cult.',
  'An ex-criminal trying to go straight, but their past keeps catching up.',
  'A flamboyant artist looking for inspiration in the stars.',
  'A jaded law enforcement officer from a high-tech metropolis.',
  'A star-ship chef who has seen too much.',
  'A washed-up journalist chasing one last big story.',
  'An idealistic diplomat trying to broker peace on the frontier.',
  'A genetically engineered former soldier seeking a new purpose.',
  'A rogue AI in a synthetic body, hiding its true nature.',
  'A seasoned cargo hauler who knows all the shortcuts and shady ports.',
  'A desperate refugee fleeing a planetary disaster.',
  'A grizzled prospector who struck it rich and is now hopelessly paranoid.',
  'A celebrity musician on a tour of the outer rim, secretly a spy.',
  'A former teacher who now leads a band of renegade students.',
  'A con artist who specializes in selling fake alien artifacts.',
  'A bounty hunter who always brings their target in alive, no matter the cost.',
  'A gambler who owes money to a powerful crime syndicate.',
  'A xenobotanist searching for a rare plant with miraculous healing properties.',
  'An archaeologist who unearthed a dangerous secret about a precursor race.',
  "A ship's doctor with a dark past and a steady hand in a crisis.",
  'A wanderer with amnesia, trying to piece together their identity from cryptic clues.',
  'A prophet who preaches about the end of the universe.',
  'A master thief who only steals from the ultra-wealthy.',
  'A retired starship captain, bored with civilian life.',
  'A cybernetically enhanced assassin trying to escape their former masters.',
  'A charismatic cult leader who promises eternal life through technology.',
  'A private investigator who specializes in missing persons cases on sprawling space stations.',
  'A struggling colonist on a newly terraformed world.',
  'A seasoned explorer mapping the uncharted regions of the galaxy.',
  'A bodyguard for a high-profile client with many enemies.',
  'A mechanic who can fix any ship with just a wrench and some colorful language.',
  'A scavenger from a low-tech world, picking over starship wrecks.',
  'A belter (asteroid miner) who has lost their claim due to corporate politics.',
  'An entertainer who performed for front-line troops and now suffers from shell shock.',
  'A professional gambler who frequents high-stakes games in the decadent casinos of the core worlds.',
  'A socialite from a capital world, slumming it on the frontier for "the experience".',
  'An Imperial Marine sergeant from the 5th Frontier War, haunted by the Battle of Mora.',
  'A Zhodani intelligence operative stranded behind Imperial lines, hiding their psionic abilities.',
  'A Free Trader captain, bankrupted when their ship was impounded at Rhylanor during the war.',
  'A Vargr corsair from the Gvurrdon Sector, seeking plunder and glory along the Imperial border. Their species is a race of humanoid canines.',
  'An Aslan ihatei (male warrior) on his lone land-grab quest in the wilds of the Spinward Marches. Their species is a race of humanoid felines.',
  'An Imperial Scout from the IISS, tasked with mapping a politically sensitive, uncharted subsector.',
  'A demobilized Imperial Army trooper with a cybernetic limb and a simmering grudge against the Zhodani.',
  'A megacorporation executive from Sternmetal Horizons, looking to exploit post-war reconstruction markets.',
  'A diplomat from the Imperial Ministry of Foreign Affairs, working on a fragile peace treaty.',
  'A Zhodani "Olympian" (covert agent) masquerading as a simple merchant to observe Imperial society.',
  'A Vargr pack leader exiled for unorthodox ideas about cooperation with other species. Their species is a race of humanoid canines.',
  "A Droyne worker drone, separated from its caste and seeking a new purpose among the 'giants'. Their species is a race of small, winged, insectoid-reptilian humanoids.",
  "An Hiver 'agent' on a mysterious mission in human space, seemingly oblivious to social cues. Their species is a radially symmetrical, starfish-like race.",
  'A Kkree naval officer from the Two Thousand Worlds, rigid and uncompromising in their military traditions. Their species is a race of large, herbivorous centauroids.',
  'An independent Sword Worlder colonist who fiercely distrusts all Imperials.',
  'A researcher from the University of Glisten, hunting for lost data from the First Imperium.',
  'A black marketeer dealing in restricted military-grade hardware scavenged from the war.',
  'A bodyguard to a paranoid megacorporation CEO who made many enemies during the war.',
  'A noble from the Lunion subsector whose family lost everything in the Zhodani advance.',
  'A private investigator specializing in finding people who went missing during the chaos of the war.',
  'A rogue merchant who broke blockades to supply besieged worlds, and is now wanted by the Imperial Navy.',
  'A former Imperial Navy gunner with a serious drinking problem and a hatred for Zhodani.',
  'An anti-Zhodani partisan from an occupied world, now struggling to adapt to peacetime.',
  'A corporate troubleshooter for Tukera Lines, navigating the dangerous politics of post-war shipping.',
  'A xenobiologist studying the dangerous fauna of a frontier world that was a former Zhodani military outpost.',
  "An Aslan clan leader's disfavored child, sent to the frontier to earn respect or die trying. Their species is a race of humanoid felines.",
  'A bounty hunter known for their discretion and relentless pursuit of war criminals.',
  'An engineer who specializes in maintaining aging, pre-war technology on a backwater planet.',
  "A master forger of ship's papers and identity documents, whose work is in high demand.",
  'A patrol officer from a system defense boat squadron, bored with peacetime duties.',
  'A former Imperial Marine cook with a surprising number of contacts in the criminal underworld.',
  'A navigator who knows secret, unlisted jump routes through dangerous, pirate-infested space.',
  "A rescue and salvage operator cleaning up the war's orbital debris fields for profit.",
  "A financier who speculates on planetary governments' debts in the chaotic post-war economy.",
  'A spy for the Zhodani Consulate posing as a cultural exchange student.',
  'A researcher studying the enigmatic Ancients, convinced they influenced the outcome of the war.',
  'An arms dealer supplying both sides of a lingering border skirmish in the Corridor sector.',
  'A political dissident from a world with an oppressive, pro-Zhodani government.',
  'A safari guide for big-game hunters on untamed worlds in the sparsely populated Lanth subsector.',
  'A mercenary scout who prefers working alone in hostile territory and has a mysterious past.',
  "A customs inspector at a high-security starport who is secretly on a megacorporation's payroll.",
  'A technician specializing in grav-vehicle repair on a world where they are the primary mode of transport.',
  "An aide to a powerful Imperial noble visiting the Marches to assess the war's damage.",
  "A corporate lawyer defending a megacorporation's claim to a newly discovered resource-rich system.",
  'A refugee camp administrator on a world flooded with those displaced by the 5th Frontier War.',
  'A covert operative for an ambitious Imperial noble, seeking to gain advantage from the post-war chaos.',
];
